pub struct OpInfo {
    pub mnemonic: &'static str,
    pub operand_size: usize,
    pub description: &'static str,
    pub category: OpCategory,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum OpCategory {
    Stop, Arithmetic, Comparison, Bitwise, Crypto,
    EnvInfo, BlockInfo, Stack, Memory, Storage,
    Control, Log, System, Push, Dup, Swap, Invalid,
}

pub fn lookup(byte: u8) -> OpInfo {
    match byte {
        0x00 => OpInfo { mnemonic: "STOP",           operand_size: 0, description: "Halts execution",                        category: OpCategory::Stop },
        0x01 => OpInfo { mnemonic: "ADD",            operand_size: 0, description: "Addition",                               category: OpCategory::Arithmetic },
        0x02 => OpInfo { mnemonic: "MUL",            operand_size: 0, description: "Multiplication",                         category: OpCategory::Arithmetic },
        0x03 => OpInfo { mnemonic: "SUB",            operand_size: 0, description: "Subtraction",                            category: OpCategory::Arithmetic },
        0x04 => OpInfo { mnemonic: "DIV",            operand_size: 0, description: "Integer division",                       category: OpCategory::Arithmetic },
        0x05 => OpInfo { mnemonic: "SDIV",           operand_size: 0, description: "Signed integer division",                category: OpCategory::Arithmetic },
        0x06 => OpInfo { mnemonic: "MOD",            operand_size: 0, description: "Modulo",                                 category: OpCategory::Arithmetic },
        0x07 => OpInfo { mnemonic: "SMOD",           operand_size: 0, description: "Signed modulo",                          category: OpCategory::Arithmetic },
        0x08 => OpInfo { mnemonic: "ADDMOD",         operand_size: 0, description: "Addition modulo N",                      category: OpCategory::Arithmetic },
        0x09 => OpInfo { mnemonic: "MULMOD",         operand_size: 0, description: "Multiplication modulo N",                category: OpCategory::Arithmetic },
        0x0a => OpInfo { mnemonic: "EXP",            operand_size: 0, description: "Exponentiation",                         category: OpCategory::Arithmetic },
        0x0b => OpInfo { mnemonic: "SIGNEXTEND",     operand_size: 0, description: "Sign extend",                            category: OpCategory::Arithmetic },
        0x10 => OpInfo { mnemonic: "LT",             operand_size: 0, description: "Less than",                              category: OpCategory::Comparison },
        0x11 => OpInfo { mnemonic: "GT",             operand_size: 0, description: "Greater than",                           category: OpCategory::Comparison },
        0x12 => OpInfo { mnemonic: "SLT",            operand_size: 0, description: "Signed less than",                       category: OpCategory::Comparison },
        0x13 => OpInfo { mnemonic: "SGT",            operand_size: 0, description: "Signed greater than",                    category: OpCategory::Comparison },
        0x14 => OpInfo { mnemonic: "EQ",             operand_size: 0, description: "Equality",                               category: OpCategory::Comparison },
        0x15 => OpInfo { mnemonic: "ISZERO",         operand_size: 0, description: "Is zero",                                category: OpCategory::Comparison },
        0x16 => OpInfo { mnemonic: "AND",            operand_size: 0, description: "Bitwise AND",                            category: OpCategory::Bitwise },
        0x17 => OpInfo { mnemonic: "OR",             operand_size: 0, description: "Bitwise OR",                             category: OpCategory::Bitwise },
        0x18 => OpInfo { mnemonic: "XOR",            operand_size: 0, description: "Bitwise XOR",                            category: OpCategory::Bitwise },
        0x19 => OpInfo { mnemonic: "NOT",            operand_size: 0, description: "Bitwise NOT",                            category: OpCategory::Bitwise },
        0x1a => OpInfo { mnemonic: "BYTE",           operand_size: 0, description: "Extract byte from word",                 category: OpCategory::Bitwise },
        0x1b => OpInfo { mnemonic: "SHL",            operand_size: 0, description: "Shift left",                             category: OpCategory::Bitwise },
        0x1c => OpInfo { mnemonic: "SHR",            operand_size: 0, description: "Logical shift right",                    category: OpCategory::Bitwise },
        0x1d => OpInfo { mnemonic: "SAR",            operand_size: 0, description: "Arithmetic shift right",                 category: OpCategory::Bitwise },
        0x20 => OpInfo { mnemonic: "KECCAK256",      operand_size: 0, description: "Keccak-256 hash",                        category: OpCategory::Crypto },
        0x30 => OpInfo { mnemonic: "ADDRESS",        operand_size: 0, description: "Address of current account",             category: OpCategory::EnvInfo },
        0x31 => OpInfo { mnemonic: "BALANCE",        operand_size: 0, description: "Balance of address",                     category: OpCategory::EnvInfo },
        0x32 => OpInfo { mnemonic: "ORIGIN",         operand_size: 0, description: "Transaction origin address",             category: OpCategory::EnvInfo },
        0x33 => OpInfo { mnemonic: "CALLER",         operand_size: 0, description: "Caller address",                         category: OpCategory::EnvInfo },
        0x34 => OpInfo { mnemonic: "CALLVALUE",      operand_size: 0, description: "Deposited value in wei",                 category: OpCategory::EnvInfo },
        0x35 => OpInfo { mnemonic: "CALLDATALOAD",   operand_size: 0, description: "Load calldata word",                     category: OpCategory::EnvInfo },
        0x36 => OpInfo { mnemonic: "CALLDATASIZE",   operand_size: 0, description: "Size of calldata",                       category: OpCategory::EnvInfo },
        0x37 => OpInfo { mnemonic: "CALLDATACOPY",   operand_size: 0, description: "Copy calldata to memory",                category: OpCategory::EnvInfo },
        0x38 => OpInfo { mnemonic: "CODESIZE",       operand_size: 0, description: "Size of code",                           category: OpCategory::EnvInfo },
        0x39 => OpInfo { mnemonic: "CODECOPY",       operand_size: 0, description: "Copy code to memory",                    category: OpCategory::EnvInfo },
        0x3a => OpInfo { mnemonic: "GASPRICE",       operand_size: 0, description: "Gas price of transaction",               category: OpCategory::EnvInfo },
        0x3b => OpInfo { mnemonic: "EXTCODESIZE",    operand_size: 0, description: "Size of external code",                  category: OpCategory::EnvInfo },
        0x3c => OpInfo { mnemonic: "EXTCODECOPY",    operand_size: 0, description: "Copy external code to memory",           category: OpCategory::EnvInfo },
        0x3d => OpInfo { mnemonic: "RETURNDATASIZE", operand_size: 0, description: "Size of return data",                    category: OpCategory::EnvInfo },
        0x3e => OpInfo { mnemonic: "RETURNDATACOPY", operand_size: 0, description: "Copy return data to memory",             category: OpCategory::EnvInfo },
        0x3f => OpInfo { mnemonic: "EXTCODEHASH",    operand_size: 0, description: "Hash of external code",                  category: OpCategory::EnvInfo },
        0x40 => OpInfo { mnemonic: "BLOCKHASH",      operand_size: 0, description: "Hash of recent block",                   category: OpCategory::BlockInfo },
        0x41 => OpInfo { mnemonic: "COINBASE",       operand_size: 0, description: "Block beneficiary address",              category: OpCategory::BlockInfo },
        0x42 => OpInfo { mnemonic: "TIMESTAMP",      operand_size: 0, description: "Block timestamp",                        category: OpCategory::BlockInfo },
        0x43 => OpInfo { mnemonic: "NUMBER",         operand_size: 0, description: "Block number",                           category: OpCategory::BlockInfo },
        0x44 => OpInfo { mnemonic: "PREVRANDAO",     operand_size: 0, description: "Previous RANDAO mix",                    category: OpCategory::BlockInfo },
        0x45 => OpInfo { mnemonic: "GASLIMIT",       operand_size: 0, description: "Block gas limit",                        category: OpCategory::BlockInfo },
        0x46 => OpInfo { mnemonic: "CHAINID",        operand_size: 0, description: "Chain ID",                               category: OpCategory::BlockInfo },
        0x47 => OpInfo { mnemonic: "SELFBALANCE",    operand_size: 0, description: "Balance of current account",             category: OpCategory::BlockInfo },
        0x48 => OpInfo { mnemonic: "BASEFEE",        operand_size: 0, description: "Base fee of current block",              category: OpCategory::BlockInfo },
        0x49 => OpInfo { mnemonic: "BLOBHASH",       operand_size: 0, description: "Blob versioned hash (EIP-4844)",         category: OpCategory::BlockInfo },
        0x4a => OpInfo { mnemonic: "BLOBBASEFEE",    operand_size: 0, description: "Blob base fee (EIP-7516)",               category: OpCategory::BlockInfo },
        0x50 => OpInfo { mnemonic: "POP",            operand_size: 0, description: "Remove top of stack",                    category: OpCategory::Stack },
        0x51 => OpInfo { mnemonic: "MLOAD",          operand_size: 0, description: "Load word from memory",                  category: OpCategory::Memory },
        0x52 => OpInfo { mnemonic: "MSTORE",         operand_size: 0, description: "Store word to memory",                   category: OpCategory::Memory },
        0x53 => OpInfo { mnemonic: "MSTORE8",        operand_size: 0, description: "Store byte to memory",                   category: OpCategory::Memory },
        0x54 => OpInfo { mnemonic: "SLOAD",          operand_size: 0, description: "Load from storage",                      category: OpCategory::Storage },
        0x55 => OpInfo { mnemonic: "SSTORE",         operand_size: 0, description: "Store to storage",                       category: OpCategory::Storage },
        0x56 => OpInfo { mnemonic: "JUMP",           operand_size: 0, description: "Unconditional jump",                     category: OpCategory::Control },
        0x57 => OpInfo { mnemonic: "JUMPI",          operand_size: 0, description: "Conditional jump",                       category: OpCategory::Control },
        0x58 => OpInfo { mnemonic: "PC",             operand_size: 0, description: "Program counter",                        category: OpCategory::Control },
        0x59 => OpInfo { mnemonic: "MSIZE",          operand_size: 0, description: "Size of active memory",                  category: OpCategory::Memory },
        0x5a => OpInfo { mnemonic: "GAS",            operand_size: 0, description: "Remaining gas",                          category: OpCategory::EnvInfo },
        0x5b => OpInfo { mnemonic: "JUMPDEST",       operand_size: 0, description: "Valid jump destination",                 category: OpCategory::Control },
        0x5c => OpInfo { mnemonic: "TLOAD",          operand_size: 0, description: "Load from transient storage (EIP-1153)", category: OpCategory::Storage },
        0x5d => OpInfo { mnemonic: "TSTORE",         operand_size: 0, description: "Store to transient storage (EIP-1153)",  category: OpCategory::Storage },
        0x5e => OpInfo { mnemonic: "MCOPY",          operand_size: 0, description: "Memory copy (EIP-5656)",                 category: OpCategory::Memory },
        0x5f => OpInfo { mnemonic: "PUSH0",          operand_size: 0, description: "Push zero onto stack",                   category: OpCategory::Push },
        n @ 0x60..=0x7f => OpInfo {
            mnemonic: PUSH_MNEMONICS[(n - 0x60) as usize],
            operand_size: (n - 0x5f) as usize,
            description: "Push N bytes onto stack",
            category: OpCategory::Push,
        },
        n @ 0x80..=0x8f => OpInfo {
            mnemonic: DUP_MNEMONICS[(n - 0x80) as usize],
            operand_size: 0,
            description: "Duplicate stack item",
            category: OpCategory::Dup,
        },
        n @ 0x90..=0x9f => OpInfo {
            mnemonic: SWAP_MNEMONICS[(n - 0x90) as usize],
            operand_size: 0,
            description: "Swap stack items",
            category: OpCategory::Swap,
        },
        0xa0 => OpInfo { mnemonic: "LOG0",         operand_size: 0, description: "Append log (0 topics)",           category: OpCategory::Log },
        0xa1 => OpInfo { mnemonic: "LOG1",         operand_size: 0, description: "Append log (1 topic)",            category: OpCategory::Log },
        0xa2 => OpInfo { mnemonic: "LOG2",         operand_size: 0, description: "Append log (2 topics)",           category: OpCategory::Log },
        0xa3 => OpInfo { mnemonic: "LOG3",         operand_size: 0, description: "Append log (3 topics)",           category: OpCategory::Log },
        0xa4 => OpInfo { mnemonic: "LOG4",         operand_size: 0, description: "Append log (4 topics)",           category: OpCategory::Log },
        0xf0 => OpInfo { mnemonic: "CREATE",       operand_size: 0, description: "Create contract",                 category: OpCategory::System },
        0xf1 => OpInfo { mnemonic: "CALL",         operand_size: 0, description: "Message call",                    category: OpCategory::System },
        0xf2 => OpInfo { mnemonic: "CALLCODE",     operand_size: 0, description: "Message call with this code",     category: OpCategory::System },
        0xf3 => OpInfo { mnemonic: "RETURN",       operand_size: 0, description: "Return from execution",           category: OpCategory::System },
        0xf4 => OpInfo { mnemonic: "DELEGATECALL", operand_size: 0, description: "Delegate call",                   category: OpCategory::System },
        0xf5 => OpInfo { mnemonic: "CREATE2",      operand_size: 0, description: "Create contract (deterministic)", category: OpCategory::System },
        0xfa => OpInfo { mnemonic: "STATICCALL",   operand_size: 0, description: "Static message call",             category: OpCategory::System },
        0xfd => OpInfo { mnemonic: "REVERT",       operand_size: 0, description: "Revert execution",                category: OpCategory::System },
        0xfe => OpInfo { mnemonic: "INVALID",      operand_size: 0, description: "Invalid instruction",             category: OpCategory::Invalid },
        0xff => OpInfo { mnemonic: "SELFDESTRUCT", operand_size: 0, description: "Self destruct contract",          category: OpCategory::System },
        _    => OpInfo { mnemonic: "UNKNOWN",      operand_size: 0, description: "Unknown opcode",                  category: OpCategory::Invalid },
    }
}

static PUSH_MNEMONICS: [&str; 32] = [
    "PUSH1","PUSH2","PUSH3","PUSH4","PUSH5","PUSH6","PUSH7","PUSH8",
    "PUSH9","PUSH10","PUSH11","PUSH12","PUSH13","PUSH14","PUSH15","PUSH16",
    "PUSH17","PUSH18","PUSH19","PUSH20","PUSH21","PUSH22","PUSH23","PUSH24",
    "PUSH25","PUSH26","PUSH27","PUSH28","PUSH29","PUSH30","PUSH31","PUSH32",
];
static DUP_MNEMONICS: [&str; 16] = [
    "DUP1","DUP2","DUP3","DUP4","DUP5","DUP6","DUP7","DUP8",
    "DUP9","DUP10","DUP11","DUP12","DUP13","DUP14","DUP15","DUP16",
];
static SWAP_MNEMONICS: [&str; 16] = [
    "SWAP1","SWAP2","SWAP3","SWAP4","SWAP5","SWAP6","SWAP7","SWAP8",
    "SWAP9","SWAP10","SWAP11","SWAP12","SWAP13","SWAP14","SWAP15","SWAP16",
];
